config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  root 'pages#home'

  resources :images

  resources :users
  post 'save', to: 'users#save'
  post 'remove', to: 'users#remove'
  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user

  def self.search(query)
    Unsplash::Photo.search(query, page = 1, per_page = 20)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.search(params[:search]) if params[:search]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def results
  end

  def search
    binding.pry
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user_path user
    else
      flash.now[:danger] = 'Uh Oh, doesnt look quite right'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @images = @user.images
  end

  def save
    @user = current_user
    @user.images << Image.create(url: params[:url])
  end

  def remove
    image = Image.find_by(url: params[:url])
    image.delete
    flash[:success] = "Image Deleted!"
    redirect_to user_path(User.find(params[:user_id]))
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Thanks for signing up!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Your account has been updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
    :password_confirmation)
  end

  def authorized
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/images/index.html.erb
<div class="container">

  <div class="row">

    <div class="col-lg-12 text-center v-center">
        <div class="input-group input-group-lg col-sm-offset-4 col-sm-4">
<h1>Images</h1>
<%= form_tag images_path, :method => 'get', id: "search-form" do %>
<p>
  <%= text_field_tag :search, params[:search], placeholder: "Search Images"  %>
  <%= submit_tag "Search", :name => nil %>
</p>
<% end %>
</div>

</div>
</div>
<% if @images %>
<% @images.each_slice(3) do |images| %>
<div class="row">
  <% images.each do |image| %>
  <div class="col-md-4">
    <%= link_to image_tag("#{image.urls.regular}",  class: "rounded float-left", width: "304", height: "236"), image.urls.full %>
    <%= button_to("Save", {:controller => "users", :action => "save", :url => image.urls.full}, class: "btn btn-primary col-md-offset-4") if logged_in? %>
  </div>
  <% end %>
</div>
<% end %>
<% end %>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Resplash", pages_home_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   pages_home_path %></li>
        <li><%= link_to "Search Images",   images_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <% if logged_in? %>
        <li><%= link_to "My Images", current_user %></li>
        <li><%= link_to "Edit Account", edit_user_path(current_user) %></li>
        <li class="divider"></li>
        <li>
          <%= link_to "Log out", logout_path, method: :delete %>
        </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <li><%= link_to "Sign Up", new_user_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Resplash</title>
  <title><%= yield(:title) %> | Resplash </title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>


</body>
</html>

app/views/pages/home.html.erb
<% provide(:title, "Home") %>
<div class="container-full">

  <div class="row">

    <div class="col-lg-12 text-center v-center">

      <h1>Resplash</h1>
      <p class="lead">Professionally done, free photos</p>

      <br>

      <form class="col-lg-12">
        <div class="input-group input-group-lg col-sm-offset-4 col-sm-4">
          <span class="input-group-btn">
            <%= link_to("Get Started", new_user_path, class: "btn btn-lg btn-primary") %>
          </span>
        </div>
      </form>
    </div>

  </div>

  <br><br><br><br><br>

</div>

<div class="container">

  <hr>

  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading"><h3>About</h3></div>
        <div class="panel-body">
          Resplash is an app that I'm working on just for fun and practice before an interview.
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading"><h3>Future</h3></div>
          <div class="panel-body">I hope to expand on it more by fixing the style and adding more functionality such as the ability to follow users and upload your own images but feel free to explore!
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading"><h3>Me</h3></div>
          <div class="panel-body">
            <%= link_to "My Github Page", "https://github.com/mitchashby16" %> <br>
            <%= link_to "My Linkedin", "https://linkedin.com/in/mitchashby" %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_current_user.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "My Profile", current_user %></span>

app/views/shared/_error.html.erb
<% if o.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(o.errors.count, "error") %>.
    </div>
    <ul>
    <% o.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
  <%= link_to user.name, user %>

app/views/users/edit.html.erb
<% provide(:title, "Edit Account") %>
<div class="container">

  <div class="row">

    <div class="col-lg-12 text-center v-center">
      <h1>Update your profile</h1>

      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_for(@user) do |f| %>
          <%= render 'shared/error', o: @user %>

          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>

          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
          <br>
          <%= f.submit "Save", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center v-center">
      <h1>Users</h1>
    </div>

    <ul class="users">
      <% @users.each do |user| %>
      <h3><%= render user %></h3>
      <br>
      <% end %>
    </ul>

  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center v-center">
      <h1>Sign up</h1>

      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_for(@user, url: signup_path) do |f| %>
          <%= render 'shared/error', o: @user %>

          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>

          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
          <br>
          <%= f.submit "Sign Up!", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center v-center">
      <section class="user_info">
        <h1>
          <%= @user.name %>
        </h1>
      </section>
    </aside>
  </div>
</div>


<% if @images %>
<% @images.each_slice(3) do |images| %>
<div class="row">
  <% images.each do |image| %>
  <div class="col-md-4">
    <%= link_to image_tag("#{image.url}",  class: "rounded float-left", width: "304", height: "236"), image.url %>
    <%= button_to("Delete", {:controller => "users", :action => "remove", :url => image.url, :user_id => @current_user.id}, class: "btn btn-danger col-md-offset-4") if current_user?(User.find_by(id: @user.id)) %>
  </div>
  <% end %>
</div>
<% end %>
<% end %>
</div>